#ifndef COM_DEF_H
#define COM_DEF_H

#include <cmath>
#include <iostream>
using std::cout;
using std::endl;

#define MAX_NSECTORS 100

#define M_2PI (2*M_PI)

#define VIEWPORT_LEFT_OFF   00
#define VIEWPORT_RIGHT_OFF  00
#define VIEWPORT_TOP_OFF    00
#define VIEWPORT_BOT_OFF    00

#define FOV 60

#define UPDATE_VP_CENTER_FACTOR 2
#define UPDATE_HEIGHT_FACTOR 2

#define PLAYER_HEIGHT 40

#define ANGLE_DISP 0.025 //0.055
#define POS_DISP 2.5

#define PLAYER_INIT_XPOS 5050
#define PLAYER_INIT_YPOS 1900
#define PLAYER_INIT_ANGLE 3 * M_PI / 2

#define FXP_SHIFT 16
#define FXP_MUL (1<<FXP_SHIFT)

#define MAX_WALL_DISTANCE 1.0


#define BWALL_CODE -1
#define COLLISION_DISTANCE 5.0
#define FIRST_SWALL_ID 100
#define FIRST_PWALL_ID -100
#define PLANE_CLIP_CODE 1
#define LIGHT_LEVEL_SPAN 15
#define LIGHT_DISTANCE 1024 //1536
#define SECTOR_LIGHT_FACTOR_M 1.1

#define DOOR_ACTIVATION_DISTANCE 15.0
#define DOOR_OPEN_TIME 100
#define DOOR_MOV_INT 2
#define DOOR_CEILING_OFF 10
#define DOOR_PLAYER_HDIFF 5

#define ELEVATOR_WAIT_TIME 100
#define ELEVATOR_MOV_INT 2

#define INF_CEILING_HEIGHT 100000

#endif